services:
  - type: web
    name: ram-mens-wears-api
    runtime: node
    rootDir: 7star-backend/7star-backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_ORIGIN
        sync: false
      - key: MONGODB_USERNAME
        sync: false
      - key: MONGODB_PASSWORD
        sync: false
